_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    UV_CONFIDENCE:
      ENABLED: True
    DECODER_ON: True
    LOSS_NAME: "DensePoseChartLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
SOLVER:
#  CLIP_GRADIENTS:
#    ENABLED: True
#  WARMUP_FACTOR: 0.025
#  MAX_ITER: 260000
#  STEPS: (200000, 240000)
#SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
