_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    LOSS_NAME: "DensePoseChartLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
